export const filterData = [
    {
      items: [
        { name: '10,000', value: '10000' },
        { name: '20,000', value: '20000' },
        { name: '30,000', value: '30000' },
        { name: '40,000', value: '40000' },
        { name: '50,000', value: '50000' },
        { name: '60,000', value: '60000' },
        { name: '85,000', value: '85000' },
      ],
      placeholder: 'Min Price(AED)',
      queryName: 'priceMin',
    },
    {
      items: [
        { name: '500,000', value: '500000' },
        { name: '600,000', value: '600000' },
        { name: '850,000', value: '850000' },
        { name: '1,100,000', value: '1100000' },
        { name: '1,350,000', value: '1350000' },
        { name: '1,600,000', value: '1600000' },
        { name: '1,850,000', value: '1850000' },
        { name: '2,000,000', value: '2000000' },
        { name: '3,000,000', value: '3000000' },
        { name: '4,000,000', value: '4000000' },
        { name: '5,000,000', value: '5000000' },
        { name: '6,000,000', value: '6000000' },
        { name: '7,000,000', value: '7000000' },
        { name: '8,000,000', value: '8000000' },
        { name: '9,000,000', value: '9000000' },
        { name: '10,000,000', value: '10000000' },
      ],
      placeholder: 'Max Price(AED)',
      queryName: 'priceMax',
    },
    {
      items: [
        { name: 'Lowest Price', value: 'price-asc' },
        { name: 'Highest Price', value: 'price-desc' },
        { name: 'Newest', value: 'date-asc' },
        { name: 'Oldest', value: 'date-desc' },
        { name: 'Verified', value: 'verified-score' },
        { name: 'City Level Score', value: 'city-level-score' },
      ],
      placeholder: 'Sort',
      queryName: 'sort',
    },
    {
    items: [
        { name: '40', value: '40' },
        { name: '50', value: '50' },
        { name: '60', value: '60' },
        { name: '70', value: '70' },
        { name: '80', value: '80' },
        { name: '90', value: '90' },
        { name: '100', value: '100' },
        { name: '200', value: '200' },
        { name: '300', value: '300' },
        { name: '400', value: '400' },
        { name: '500', value: '500' },
        { name: '1000', value: '1000' },
        { name: '2000', value: '2000' },
    ],
    placeholder: 'Min Area(sqft)',
    queryName: 'areaMin',
    },
    {
      items: [
        { name: '40', value: '40' },
        { name: '50', value: '50' },
        { name: '60', value: '60' },
        { name: '70', value: '70' },
        { name: '80', value: '80' },
        { name: '90', value: '90' },
        { name: '100', value: '100' },
        { name: '200', value: '200' },
        { name: '300', value: '300' },
        { name: '400', value: '400' },
        { name: '500', value: '500' },
        { name: '1000', value: '1000' },
        { name: '2000', value: '2000' },
      ],
      placeholder: 'Max Area(sqft)',
      queryName: 'areaMax',
    },
    {
      items: [
        { name: '1', value: '1' },
        { name: '2', value: '2' },
        { name: '3', value: '3' },
        { name: '4', value: '4' },
        { name: '5', value: '5' },
        { name: '6', value: '6' },
        { name: '7', value: '7' },
        { name: '8', value: '8' },
        { name: '9', value: '9' },
        { name: '10', value: '10' },
      ],
      placeholder: 'Min Rooms',
      queryName: 'roomsMin',
    },
    {
        items: [
          { name: '1', value: '1' },
          { name: '2', value: '2' },
          { name: '3', value: '3' },
          { name: '4', value: '4' },
          { name: '5', value: '5' },
          { name: '6', value: '6' },
          { name: '7', value: '7' },
          { name: '8', value: '8' },
          { name: '9', value: '9' },
          { name: '10', value: '10' },
        ],
        placeholder: 'Max Rooms',
        queryName: 'roomsMax',
    },
    {
      items: [
        { name: '1', value: '1' },
        { name: '2', value: '2' },
        { name: '3', value: '3' },
        { name: '4', value: '4' },
        { name: '5', value: '5' },
        { name: '6', value: '6' },
        { name: '7', value: '7' },
        { name: '8', value: '8' },
        { name: '9', value: '9' },
        { name: '10', value: '10' },
      ],
      placeholder: 'Min Baths',
      queryName: 'bathsMin',
    },
    {
        items: [
          { name: '1', value: '1' },
          { name: '2', value: '2' },
          { name: '3', value: '3' },
          { name: '4', value: '4' },
          { name: '5', value: '5' },
          { name: '6', value: '6' },
          { name: '7', value: '7' },
          { name: '8', value: '8' },
          { name: '9', value: '9' },
          { name: '10', value: '10' },
        ],
        placeholder: 'Max Baths',
        queryName: 'bathsMax',
      },
    {
      items: [
        { name: 'Furnished', value: 'furnished' },
        { name: 'Unfurnished', value: 'unfurnished' },
      ],
      placeholder: 'Furnish Type',
      queryName: 'furnishingStatus',
    },
    {
      items: [
        { name: 'Apartment', value: '4' },
        { name: 'Townhouses', value: '16' },
        { name: 'Villas', value: '3' },
        { name: 'Penthouses', value: '18' },
        { name: 'Hotel Apartments', value: '21' },
        { name: 'Villa Compound', value: '19' },
        { name: 'Residential Plot', value: '14' },
        { name: 'Residential Floor', value: '12' },
        { name: 'Residential Building', value: '17' },
      ],
      placeholder: 'Property Type',
      queryName: 'categoryExternalID',
    },
  ];
  
  